image: thyrlian/android-sdk

before_script:
  - chmod +x gradlew
  
stages:
  - build

build:
  stage: build
  script:
    - ./changeVersion.sh app/build.gradle " $CI_COMMIT_REF_NAME\_$CI_PIPELINE_ID" --append
    - ./gradlew assembleDebug --stacktrace
  artifacts:
    paths:
    - app/build/outputs/apk/debug/app-debug.apk
  except:
    - /^no_ci.*$/
    - /^no_build.*$/
    - /^no_build_no_tests.*$/
    - /^no_build_no_deploy.*$/
    - release
    
build_release:
  stage: build
  script:
   - ./gradlew clean check assembleRelease --stacktrace -Pandroid.injected.signing.store.file=$KEYSTORE_FILE -Pandroid.injected.signing.store.password=$KEYSTORE_PASSWORD -Pandroid.injected.signing.key.alias=$KEYSTORE_KEY_NAME -Pandroid.injected.signing.key.password=$KEYSTORE_KEY_PASSWORD -x test
  artifacts:
    paths:
    - app/build/outputs/apk/release/app-release.apk

#upload:
#  stage: webdeploy
#  script:
#    - cp -f app/build/outputs/apk/debug/app-debug.apk $DEV_DEPLOY_DIR/$CI_COMMIT_REF_NAME-$CI_PIPELINE_ID.apk
#    - /./home/public/gitrunner/logCIBuilds.sh $DEV_DEPLOY_DIR
#    - ln -s -f $DEV_DEPLOY_DIR/$CI_COMMIT_REF_NAME-$CI_PIPELINE_ID.apk $DEV_DEPLOY_DIR/0_latest_$CI_COMMIT_REF_NAME.apk
#  except:
#    - /^no_ci.*$/
#    - /^no_deploy.*$/
#    - /^no_tests_no_deploy.*$/
#    - /^no_build_no_deploy.*$/
#    - /^no_build.*$/
#    - release
#  artifacts:
#    paths:
#    - $DEV_DEPLOY_DIR/$CI_COMMIT_REF_NAME-$CI_PIPELINE_ID.apk
    
#upload_release:
#  stage: webdeploy
#  script:
#    - cp -f app/build/outputs/apk/release/app-release.apk $RELEASE_DEPLOY_DIR/$(/./home/public/gitrunner/determineAppVersionName.sh app/build/outputs/apk/release/app-release.apk).apk
#  only:
#    - release

#functionalTests:
#  stage: test
#  script:
#    - if [ ! -a `~/.android/avd/${AVD_NAME}.ini`]; then echo no | /home/public/android-sdk-linux/tools/android create avd -n ${AVD_NAME} -t android-${ANDROID_COMPILE_SDK} --abi google_apis/x86; fi
#    - /home/public/android-sdk-linux/tools/emulator64-x86 -avd test -no-window -no-audio &
#    - /./home/public/android-sdk-linux/wait-for-emulator.sh
#    - adb shell input keyevent 82
#    - ./gradlew cAT
#  artifacts:
#    paths:
#    - app/build/reports/androidTests/